version: '3.8'

services:
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose the app on port 3000
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/app
    depends_on:
      - db  # Ensure MySQL starts before the app
    networks:
      - app-network
    command: npm run start:dev
    
  db:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: mysql
      DB_DATABASE: '${DB_DATABASE}'
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    command: redis-server --appendonly yes  # Enable data persistence
    volumes:
      - redis-data:/data  # Persist Redis data
    networks:
      - app-network
volumes:
  db-data:
  redis-data:

networks:
  app-network:
    driver: bridge
