apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      containers:
        - name: social-container
          image: docker.io/daothevinh123/social:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: social-service
spec:
  type: LoadBalancer
  selector:
    app: social
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
