name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build NestJS application
        run: npm run build

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

  # deploy:
  #   needs: docker-build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Deploy to server
  #       run: |
  #         ssh user@your-server-ip 'docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest'
  #         ssh user@your-server-ip 'docker-compose down'
  #         ssh user@your-server-ip 'docker-compose up -d'
