name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build NestJS application
        run: npm run build

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.REPO_NAME }}"
          echo "Building Docker Image: $IMAGE_NAME:latest"
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.REPO_NAME }}"
          echo "Pushing Docker Image: $IMAGE_NAME:latest"
          docker push $IMAGE_NAME:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sử dụng phiên bản mới của action setup-gcloud, có hỗ trợ tự động cài đặt plugin gke-gcloud-auth-plugin.
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.7.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          install_components: "gke-gcloud-auth-plugin"

      - name: Create kubeconfig file
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "Kubeconfig file created successfully"

      - name: Authenticate with Kubernetes Cluster
        run: |
          kubectl config view
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/nestjs-app
          kubectl get services
